# Generated by Django 6.0.7 on 2026-07-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source_name', models.CharField(max_length=255)),
                ('evidence_summary', models.TextField()),
                ('url', models.URLField(unique=True)),
                ('publisher_year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_text', models.TextField()),
                ('verification_status', models.CharField(choices=[('true', 'True'), ('false', 'False'), ('misleading', 'Misleading'), ('insufficient', 'Insufficient Evidence')], max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('explanation', models.TextField()),
                ('search_keyword', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('references', models.ManyToManyField(related_name='claims', to='medical.medicalreference')),
            ],
        ),
    ]
