# Generated by Django 6.0.7 on 2026-08-05 18:12

from django.db import migrations
def add_references(apps,schema_editor):
    Reference=apps.get_model(
        "medical",
        "MedicalReference",
    )
    Reference.objects.bulk_create([
    Reference(
        title="AAO Fact Sheet on Carrots & Eyesight",
        source_name="AAO",
        evidence_summary="Carrots provide vitamin A but do not dramatically improve normal vision.",
        url="https://www.aao.org",
        publisher_year=2023,
    ),
    Reference(
        title="CDC Guidance on Energy Drinks & Sleep",
        source_name="CDC",
        evidence_summary="Energy drinks may temporarily increase alertness but cannot replace adequate sleep.",
        url="https://www.cdc.gov",
        publisher_year=2023,
    ),
    Reference(
        title="CDC Guidance on Antibiotic Use",
        source_name="CDC",
        evidence_summary="Stopping antibiotics early may contribute to treatment failure and resistance.",
        url="https://www.cdc.gov/antibiotic-use",
        publisher_year=2023,
    ),
    Reference(
        title="CDC Fact Sheet on Chickenpox in Adults",
        source_name="CDC",
        evidence_summary="Adults are at higher risk of severe complications from chickenpox.",
        url="https://www.cdc.gov/chickenpox",
        publisher_year=2023,
    ),
    Reference(
        title="CDC Guidance on Obesity & Diabetes Risk",
        source_name="CDC",
        evidence_summary="Obesity is a major risk factor for type 2 diabetes.",
        url="https://www.cdc.gov/diabetes",
        publisher_year=2023,
    ),
    Reference(
        title="CDC Information on Cold Weather & Flu",
        source_name="CDC",
        evidence_summary="Influenza is caused by influenza viruses, not cold temperatures.",
        url="https://www.cdc.gov/flu",
        publisher_year=2023,
    ),
    Reference(
        title="CDC Misconceptions about Flu Vaccines",
        source_name="CDC",
        evidence_summary="Flu vaccines cannot cause influenza because they do not contain live virus capable of causing infection.",
        url="https://www.cdc.gov/flu/prevent/misconceptions.htm",
        publisher_year=2023,
    ),
    Reference(
        title="CDC Handwashing & Disease Prevention",
        source_name="CDC",
        evidence_summary="Proper handwashing removes germs and significantly lowers disease transmission.",
        url="https://www.cdc.gov/handwashing",
        publisher_year=2023,
    ),
    Reference(
        title="CDC HPV Vaccine & Cancer Prevention",
        source_name="CDC",
        evidence_summary="HPV vaccination significantly reduces cervical cancer risk.",
        url="https://www.cdc.gov/hpv",
        publisher_year=2023,
    ),
    Reference(
        title="CDC Measles & Complications Guidance",
        source_name="CDC",
        evidence_summary="Measles can cause severe complications including pneumonia and encephalitis.",
        url="https://www.cdc.gov/measles",
        publisher_year=2023,
    ),
    Reference(
        title="CDC Sleep Deprivation & Health Impact",
        source_name="CDC",
        evidence_summary="Chronic sleep deprivation is associated with many health problems.",
        url="https://www.cdc.gov/sleep",
        publisher_year=2023,
    ),
    Reference(
        title="CDC Tobacco, Smoking & Secondhand Smoke",
        source_name="CDC",
        evidence_summary="Smoking is the leading cause of lung cancer and many other diseases. Exposure to secondhand smoke increases disease risk.",
        url="https://www.cdc.gov/tobacco",
        publisher_year=2023,
    ),
    Reference(
        title="CDC Vaccine Safety Concerns regarding Autism",
        source_name="CDC",
        evidence_summary="Large scientific studies have found no evidence linking vaccines to autism.",
        url="https://www.cdc.gov/vaccinesafety/concerns/autism.html",
        publisher_year=2023,
    ),
    Reference(
        title="Diabetes UK Guidance on Cinnamon & Diabetes",
        source_name="Diabetes UK",
        evidence_summary="Cinnamon may have minor effects on blood sugar but does not cure diabetes.",
        url="https://www.diabetes.org.uk",
        publisher_year=2023,
    ),
    Reference(
        title="American Heart Association Hypertension Symptoms",
        source_name="American Heart Association",
        evidence_summary="Hypertension is often called the silent killer because many people have no symptoms.",
        url="https://www.heart.org",
        publisher_year=2023,
    ),
    Reference(
        title="NCCIH / NIH Guidance on Supplements & Vitamin C",
        source_name="NIH",
        evidence_summary="Vitamin C may slightly shorten cold duration but does not prevent most colds. Natural products may cause side effects or interact with medications.",
        url="https://www.nccih.nih.gov",
        publisher_year=2023,
    ),
    Reference(
        title="NHS Guidance on Colds, Air Conditioning & Vitamin D",
        source_name="NHS",
        evidence_summary="Colds are caused by viruses, not air conditioners. Vitamin D can also be obtained through diet and supplements.",
        url="https://www.nhs.uk",
        publisher_year=2023,
    ),
    Reference(
        title="NIDDK / NIH Fact Sheet on Stomach Ulcers",
        source_name="NIH",
        evidence_summary="Most stomach ulcers are caused by H. pylori infection or NSAID use.",
        url="https://www.niddk.nih.gov",
        publisher_year=2023,
    ),
    Reference(
        title="WHO Health Topics & Public Health Fact Sheets",
        source_name="WHO",
        evidence_summary="Hydration is important but does not cure COVID-19. Regular physical activity lowers cardiovascular risk. There is no evidence that COVID-19 vaccines contain tracking devices. Misuse of antibiotics accelerates antimicrobial resistance. Modern antiretroviral therapy allows many people with HIV to live long healthy lives. Breastfeeding supports nutrition and immune protection. Malaria is transmitted by infected Anopheles mosquitoes. Exercise can reduce symptoms of anxiety and depression.",
        url="https://www.who.int",
        publisher_year=2023,
    ),
    Reference(
        title="WHO Fact Sheet on Antimicrobial Resistance",
        source_name="WHO",
        evidence_summary="Antibiotics only treat bacterial infections and are ineffective against viruses.",
        url="https://www.who.int/news-room/fact-sheets/detail/antimicrobial-resistance",
        publisher_year=2023,
    ),
])
def add_claims(apps, schema_editor):
    MedicalClaim= apps.get_model(
        "medical",
        "MedicalClaim"
    )
    MedicalClaim.objects.bulk_create([
    MedicalClaim(
        claim_text="Vaccines cause autism.",
        verification_status="False",
        risk_level="High",
        explanation="Large scientific studies have found no evidence linking vaccines to autism.",
        search_keyword="vaccines autism",
        # references=1,
    ),
    MedicalClaim(
        claim_text="Antibiotics work against viruses.",
        verification_status="False",
        risk_level="High",
        explanation="Antibiotics only treat bacterial infections and are ineffective against viruses.",
        search_keyword="antibiotics viruses",
        # references=2,
    ),
    MedicalClaim(
        claim_text="The flu vaccine can give you the flu.",
        verification_status="False",
        risk_level="Medium",
        explanation="Flu vaccines cannot cause influenza because they do not contain live virus capable of causing infection.",
        search_keyword="flu vaccine flu",
        # references=3,
    ),
    MedicalClaim(
        claim_text="Smoking increases the risk of lung cancer.",
        verification_status="True",
        risk_level="High",
        explanation="Smoking is the leading cause of lung cancer and many other diseases.",
        search_keyword="smoking lung cancer",
        # references=4,
    ),
    MedicalClaim(
        claim_text="Handwashing reduces the spread of infectious diseases.",
        verification_status="True",
        risk_level="Medium",
        explanation="Proper handwashing removes germs and significantly lowers disease transmission.",
        search_keyword="handwashing infection prevention",
        # references=5,
    ),
    MedicalClaim(
        claim_text="Drinking plenty of water cures COVID-19.",
        verification_status="False",
        risk_level="Medium",
        explanation="Hydration is important but does not cure COVID-19.",
        search_keyword="water cure covid",
        # references=6,
    ),
    MedicalClaim(
        claim_text="Diabetes can be cured by eating cinnamon.",
        verification_status="False",
        risk_level="Medium",
        explanation="Cinnamon may have minor effects on blood sugar but does not cure diabetes.",
        search_keyword="cinnamon diabetes cure",
        # references=7,
    ),
    MedicalClaim(
        claim_text="High blood pressure usually has no symptoms.",
        verification_status="True",
        risk_level="Medium",
        explanation="Hypertension is often called the silent killer because many people have no symptoms.",
        search_keyword="hypertension symptoms",
        # references=8,
    ),
    MedicalClaim(
        claim_text="Vitamin C prevents the common cold.",
        verification_status="Partially True",
        risk_level="Low",
        explanation="Vitamin C may slightly shorten cold duration but does not prevent most colds.",
        search_keyword="vitamin c cold",
        # references=9,
    ),
    MedicalClaim(
        claim_text="Exercise reduces the risk of heart disease.",
        verification_status="True",
        risk_level="Medium",
        explanation="Regular physical activity lowers cardiovascular risk.",
        search_keyword="exercise heart disease",
        # references=6,
    ),
    MedicalClaim(
        claim_text="COVID-19 vaccines contain microchips.",
        verification_status="False",
        risk_level="High",
        explanation="There is no evidence that COVID-19 vaccines contain tracking devices.",
        search_keyword="covid vaccine microchip",
        # references=6,
    ),
    MedicalClaim(
        claim_text="Measles is a harmless childhood illness.",
        verification_status="False",
        risk_level="High",
        explanation="Measles can cause severe complications including pneumonia and encephalitis.",
        search_keyword="measles complications",
        # references=10,
    ),
    MedicalClaim(
        claim_text="Obesity increases the risk of type 2 diabetes.",
        verification_status="True",
        risk_level="Medium",
        explanation="Obesity is a major risk factor for type 2 diabetes.",
        search_keyword="obesity diabetes",
        # references=11,
    ),
    MedicalClaim(
        claim_text="Using antibiotics without prescription contributes to antibiotic resistance.",
        verification_status="True",
        risk_level="High",
        explanation="Misuse of antibiotics accelerates antimicrobial resistance.",
        search_keyword="antibiotic resistance",
        # references=6,
    ),
    MedicalClaim(
        claim_text="People with HIV cannot live long healthy lives.",
        verification_status="False",
        risk_level="Medium",
        explanation="Modern antiretroviral therapy allows many people with HIV to live long healthy lives.",
        search_keyword="HIV life expectancy",
        # references=6,
    ),
    MedicalClaim(
        claim_text="HPV vaccines help prevent cervical cancer.",
        verification_status="True",
        risk_level="Medium",
        explanation="HPV vaccination significantly reduces cervical cancer risk.",
        search_keyword="HPV vaccine cervical cancer",
        # references=12,
    ),
    MedicalClaim(
        claim_text="Air conditioners cause colds.",
        verification_status="False",
        risk_level="Low",
        explanation="Colds are caused by viruses, not air conditioners.",
        search_keyword="air conditioner cold",
        # references=13,
    ),
    MedicalClaim(
        claim_text="Sun exposure is the only source of vitamin D.",
        verification_status="False",
        risk_level="Low",
        explanation="Vitamin D can also be obtained through diet and supplements.",
        search_keyword="vitamin d sources",
        # references=13,
    ),
    MedicalClaim(
        claim_text="Secondhand smoke is harmful.",
        verification_status="True",
        risk_level="High",
        explanation="Exposure to secondhand smoke increases disease risk.",
        search_keyword="secondhand smoke",
        # references=4,
    ),
    MedicalClaim(
        claim_text="Stress alone directly causes stomach ulcers.",
        verification_status="False",
        risk_level="Medium",
        explanation="Most stomach ulcers are caused by H. pylori infection or NSAID use.",
        search_keyword="stress ulcers",
        # references=14,
    ),
    MedicalClaim(
        claim_text="Sleeping less than six hours regularly can harm health.",
        verification_status="True",
        risk_level="Medium",
        explanation="Chronic sleep deprivation is associated with many health problems.",
        search_keyword="sleep deprivation",
        # references=15,
    ),
    MedicalClaim(
        claim_text="All natural products are safe.",
        verification_status="False",
        risk_level="Medium",
        explanation="Natural products may cause side effects or interact with medications.",
        search_keyword="natural supplements safety",
        # references=9,
    ),
    MedicalClaim(
        claim_text="Breastfeeding provides health benefits for infants.",
        verification_status="True",
        risk_level="Low",
        explanation="Breastfeeding supports nutrition and immune protection.",
        search_keyword="breastfeeding benefits",
        # references=6,
    ),
    MedicalClaim(
        claim_text="Eating carrots dramatically improves eyesight.",
        verification_status="Partially True",
        risk_level="Low",
        explanation="Carrots provide vitamin A but do not dramatically improve normal vision.",
        search_keyword="carrots eyesight",
        # references=16,
    ),
    MedicalClaim(
        claim_text="Mosquitoes can transmit malaria.",
        verification_status="True",
        risk_level="High",
        explanation="Malaria is transmitted by infected Anopheles mosquitoes.",
        search_keyword="malaria transmission",
        # references=6,
    ),
    MedicalClaim(
        claim_text="Cold weather alone causes the flu.",
        verification_status="False",
        risk_level="Medium",
        explanation="Influenza is caused by influenza viruses, not cold temperatures.",
        search_keyword="cold weather flu",
        # references=17,
    ),
    MedicalClaim(
        claim_text="Regular physical activity improves mental health.",
        verification_status="True",
        risk_level="Low",
        explanation="Exercise can reduce symptoms of anxiety and depression.",
        search_keyword="exercise mental health",
        # references=6,
    ),
    MedicalClaim(
        claim_text="You should stop taking antibiotics once you feel better.",
        verification_status="False",
        risk_level="High",
        explanation="Stopping antibiotics early may contribute to treatment failure and resistance.",
        search_keyword="finish antibiotics",
        # references=18,
    ),
    MedicalClaim(
        claim_text="Chickenpox can cause serious complications in adults.",
        verification_status="True",
        risk_level="Medium",
        explanation="Adults are at higher risk of severe complications from chickenpox.",
        search_keyword="chickenpox adults",
        # references=19,
    ),
    MedicalClaim(
        claim_text="Energy drinks are a safe replacement for sleep.",
        verification_status="False",
        risk_level="Medium",
        explanation="Energy drinks may temporarily increase alertness but cannot replace adequate sleep.",
        search_keyword="energy drinks sleep",
        # references=20,
    ),
])
def add_relationships(apps, schema_editor):

    MedicalClaim = apps.get_model(
        "medical",
        "MedicalClaim"
    )

    MedicalReference = apps.get_model(
        "medical",
        "MedicalReference"
    )

    relationships = [
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
        (6, 6),
        (7, 7),
        (8, 8),
        (9, 9),
        (10, 6),
        (11, 6),
        (12, 10),
        (13, 11),
        (14, 6),
        (15, 6),
        (16, 12),
        (17, 13),
        (18, 13),
        (19, 4),
        (20, 14),
        (21, 15),
        (22, 9),
        (23, 6),
        (24, 16),
        (25, 6),
        (26, 17),
        (27, 6),
        (28, 18),
        (29, 19),
        (30, 20),
    ]


    for claim_id, reference_id in relationships:

        claim = MedicalClaim.objects.get(
            id=claim_id
        )

        reference = MedicalReference.objects.get(
            id=reference_id
        )

        claim.references.add(reference)
class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_references),
        migrations.RunPython(add_claims),
        migrations.RunPython(add_relationships),

    ]
