# Generated by Django 6.0.7 on 2026-08-05 18:07

from django.db import migrations
def add_conditions(apps, schema_editor):
    ChronicCondition = apps.get_model(
        "accounts",
        "ChronicCondition"
    )

    ChronicCondition.objects.bulk_create([
    ChronicCondition(name="Diabetes Mellitus"),
    ChronicCondition(name="Hypertension"),
    ChronicCondition(name="Asthma"),
    ChronicCondition(name="Heart Disease"),
    ChronicCondition(name="Coronary Artery Disease"),
    ChronicCondition(name="Chronic Kidney Disease"),
])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
         migrations.RunPython(add_conditions),
    ]


